@echo off
echo Cleaning up...
python setup.py clean --all
if %ERRORLEVEL% neq 0 (
    echo [Error] Cleaning failed. Exiting...
    exit /b %ERRORLEVEL%
)
echo Building extension...
python setup.py build_ext --inplace
if %ERRORLEVEL% neq 0 (
    echo [Error] Building extension failed. Exiting...
    exit /b %ERRORLEVEL%
)
echo Building exe...
pyinstaller --onefile --clean --name echoof --icon=assets/echoof.ico --hidden-import echoof.cli --hidden-import echoof.base --hidden-import echoof.logger echoof_launcher.py
if %ERRORLEVEL% neq 0 (
    echo [Error] Building exe failed. Exiting...
    exit /b %ERRORLEVEL%
)
echo Building installer...
wix build installer.wxs -arch x64 -out ECHOOF.msi
if %ERRORLEVEL% neq 0 (
    echo [Error] Creating installer failed. Exiting...
    exit /b %ERRORLEVEL%
)
echo Generating WinGet Manifest...
python generate_winget_manifest.py
if %ERRORLEVEL% neq 0 (
    echo [Error] Creating WinGet manifest failed. Exiting...
    exit /b %ERRORLEVEL%
)
